#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Determine the location of the script
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

# Function to set the maximum file descriptor limit.
limit_max_fd() {
    if [ "$MAX_FD" = "maximum" ]; then
        # Use the maximum file descriptor limit (soft/hard)
        MAX_FD=`ulimit -H -n`
        if [ $? -ne 0 ]; then
            MAX_FD=`ulimit -S -n`
        fi
    fi

    ulimit -n $MAX_FD > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Could not set maximum file descriptor limit: $MAX_FD"
    fi
}

# Increase the maximum file descriptors if possible
if [ "$OSTYPE" != "cygwin" ] && [ "$OSTYPE" != "msys" ] ; then
    limit_max_fd
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    JAVA_CMD="$JAVA_HOME/bin/java"
else
    JAVA_CMD="java"
fi

exec "$JAVA_CMD" \
  $DEFAULT_JVM_OPTS \
  $JAVA_OPTS \
  $GRADLE_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
